function! TestFiletype(filetype)
  call Log('Loading ' . a:filetype . ' filetype...')

  try
    enew
    exec 'set ft=' . a:filetype
  catch
    echo 'Failed to load ' . a:filetype  . ' filetype...'
    echo v:exception
  endtry
endfunction

" DO NOT EDIT CODE BELOW, IT IS GENERATED WITH MAKEFILE

call TestFiletype('automake')
call TestFiletype('awk')
call TestFiletype('cfg')
call TestFiletype('cpp')
call TestFiletype('c')
call TestFiletype('cmake')
call TestFiletype('yaml')
call TestFiletype('Dockerfile')
call TestFiletype('yaml.docker-compose')
call TestFiletype('fish')
call TestFiletype('gitconfig')
call TestFiletype('gitrebase')
call TestFiletype('gitsendemail')
call TestFiletype('gitcommit')
call TestFiletype('javascript')
call TestFiletype('flow')
call TestFiletype('javascriptreact')
call TestFiletype('graphql')
call TestFiletype('groovy')
call TestFiletype('i3config')
call TestFiletype('Jenkinsfile')
call TestFiletype('json5')
call TestFiletype('json')
call TestFiletype('jsonnet')
call TestFiletype('jst')
call TestFiletype('llvm')
call TestFiletype('tablegen')
call TestFiletype('lua')
call TestFiletype('markdown')
call TestFiletype('nim')
call TestFiletype('objc')
call TestFiletype('ocaml')
call TestFiletype('omake')
call TestFiletype('opam')
call TestFiletype('oasis')
call TestFiletype('dune')
call TestFiletype('ocamlbuild_tags')
call TestFiletype('ocpbuild')
call TestFiletype('ocpbuildroot')
call TestFiletype('sexplib')
call TestFiletype('rc')
call TestFiletype('perl')
call TestFiletype('pod')
call TestFiletype('mason')
call TestFiletype('tt2')
call TestFiletype('tt2html')
call TestFiletype('xs')
call TestFiletype('python')
call TestFiletype('requirements')
call TestFiletype('qmake')
call TestFiletype('reason')
call TestFiletype('rst')
call TestFiletype('rust')
call TestFiletype('conf')
call TestFiletype('sh')
call TestFiletype('zsh')
call TestFiletype('tmux')
call TestFiletype('typescript')
call TestFiletype('typescriptreact')
call TestFiletype('xml')
call TestFiletype('help')
call TestFiletype('gitignore')
call TestFiletype('sql')
call TestFiletype('named')
call TestFiletype('config')
call TestFiletype('diff')
call TestFiletype('dot')
call TestFiletype('gdb')
call TestFiletype('ldif')
call TestFiletype('ld')
call TestFiletype('loginaccess')
call TestFiletype('logindefs')
call TestFiletype('mail')
call TestFiletype('mailaliases')
call TestFiletype('mailcap')
call TestFiletype('messages')
call TestFiletype('neomuttrc')
call TestFiletype('netrc')
call TestFiletype('passwd')
call TestFiletype('readline')
call TestFiletype('sass')
call TestFiletype('screen')
call TestFiletype('sshconfig')
call TestFiletype('sshdconfig')
call TestFiletype('terminfo')
call TestFiletype('udevconf')
call TestFiletype('udevperm')
call TestFiletype('vim')
call TestFiletype('viminfo')
call TestFiletype('xdefaults')
call TestFiletype('xmodmap')
call TestFiletype('crontab')
call TestFiletype('text')
call TestFiletype('pullrequest')
call TestFiletype('html')

" DO NOT EDIT CODE ABOVE, IT IS GENERATED WITH MAKEFILE
